name: Release Distributables

on:
  release:
    types:
      - published

jobs:
  build-n-upload:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bitmart-python-sdk-api
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install wheel
    - name: Build new distributables
      run: python setup.py sdist bdist_wheel
    - name: Upload distributables to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Post release cleaning
      run: |
        python setup.py clean --all
        rm dist/*